[package]
name = "adder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 添加库的路径依赖
add-one = { path = "../add-one" }
add-two = { path = "../add-two" }
rand = "0.5.5"